= BUNJANG API Guide
mins1031;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[resources-login]]
== 로그인-JWT

이메일과 비밀번호를 통해 JWT 토큰 방식의 로그인을 진행한다

operation::login[snippets='http-request,request-headers,request-fields,request-body,response-headers,response-fields,response-body']

[[resources-login]]
== 회원가입 - 임시

개인정보 입력을 통해 임시회원 가입을 진행한다.

operation::email-temp-join[snippets='http-request,request-headers,request-fields,request-body,response-headers,response-fields,response-body']

[[resources-login]]
== 이메일 인증

이메일로 전송된 토큰으로 본인인증을 진행한다.

operation::confirm-email[snippets='http-request,request-headers,request-parameters,response-headers,response-fields,response-body']

[[resources-login]]
== 회원가입

이메일 인증후 정식회원으로 가입된다.

operation::email-join[snippets='http-request,request-headers,request-fields,request-body,response-headers,response-fields,response-body']

[[resources-login]]
== 상점 생성

회원가입후 상점을 생성한다.

operation::store-create[snippets='http-request,request-headers,request-fields,request-body,response-headers,response-fields,response-body']

[[resources-login]]
== 상점 소개글 변경

상점의 소개글을 변경한다.

operation::store-introduceContent-update[snippets='http-request,request-headers,request-fields,request-body,response-headers,response-fields,response-body']

[[resources-login]]
== 상점이름 변경

상점의 이름을 변경한다.

operation::store-name-update[snippets='http-request,request-headers,request-fields,request-body,response-headers,response-fields,response-body']

[[resources-login]]
== 상점 방문자 증가

상점의 방문자 카운트룰 중가시킨다.

operation::store-plusVisitor[snippets='http-request,request-headers,request-fields,request-body,response-headers,response-fields,response-body']


[[resources-login]]
== 상점 문의 생성

상점에 대한 문의를 생성한다.

operation::storeInquiry-create[snippets='http-request,request-headers,request-fields,request-body,response-headers,response-fields,response-body']

[[resources-login]]
== 상점 문의 목록 조회

상점에 대한 상점문의 목록을 조회한다.

operation::storeInquiry-findByOwner[snippets='http-request,request-headers,path-parameters,response-headers,response-body']

[[resources-login]]
== 상점 문의 삭제

회원가입후 상점을 생성한다.f

operation::storeInquiry-delete[snippets='http-request,request-headers,path-parameters,response-headers,response-fields,response-body']

[[resources-login]]
== 상점 후기 생성

상점후기를 생성한다.

operation::storeReview-create[snippets='http-request,request-headers,request-fields,request-body,response-headers,response-fields,response-body']

[[resources-login]]
== 상점 후기 조회

상점의 후기들을 조회한다.

operation::storeReview-findByOwner[snippets='http-request,request-headers,path-parameters,response-headers,response-body']

[[resources-login]]
== 상점 후기 변경

상점후기를 변경한다.

operation::storeReview-update[snippets='http-request,request-headers,request-fields,request-body,response-headers,response-fields,response-body']

[[resources-login]]
== 상점 후기 삭제

상점후기를 삭제한다.

operation::storeReview-delete[snippets='http-request,request-headers,path-parameters,response-headers,response-fields,response-body']

[[resources-login]]
== 찜목록 상품 생성(추가)

찜목록에 상품을 생성한다

operation::wishProduct-create[snippets='http-request,request-headers,request-fields,request-body,response-headers,response-fields,response-body']

[[resources-login]]
== 찜목록 상품(들) 삭제

찜목록에 상품(들)을 삭제한다.

operation::wishProduct-delete[snippets='http-request,request-headers,request-fields,request-body,response-headers,response-fields,response-body']

