package com.min.bunjang.category.real;

import com.min.bunjang.category.model.FirstProductCategory;
import com.min.bunjang.category.model.SecondProductCategory;
import com.min.bunjang.category.model.ThirdProductCategory;
import com.min.bunjang.category.repository.FirstProductCategoryRepository;
import com.min.bunjang.category.repository.SecondProductCategoryRepository;
import com.min.bunjang.category.repository.ThirdProductCategoryRepository;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Arrays;
import java.util.List;

@SpringBootTest
public class CategoryInsertDataInRealDB {
    @Autowired
    private FirstProductCategoryRepository firstProductCategoryRepository;

    @Autowired
    private SecondProductCategoryRepository secondProductCategoryRepository;

    @Autowired
    private ThirdProductCategoryRepository thirdProductCategoryRepository;


    @DisplayName("실제 카테고리 데이터 입력")
    @Disabled
    @Test
    void create_category_in_realLocalDB() {
        List<FirstProductCategory> firstProductCategories1 = firstProductCategoryRepository.saveAll(Arrays.asList(
                FirstProductCategory.createFirstProductCategory("여성의류"),
                FirstProductCategory.createFirstProductCategory("남성의류"),
                FirstProductCategory.createFirstProductCategory("신발"),
                FirstProductCategory.createFirstProductCategory("가방"),
                FirstProductCategory.createFirstProductCategory("시계/주얼리"),
                FirstProductCategory.createFirstProductCategory("패션 액세서리"),
                FirstProductCategory.createFirstProductCategory("디지털/가전"),
                FirstProductCategory.createFirstProductCategory("스포츠/레저"),
                FirstProductCategory.createFirstProductCategory("차량/오토바이"),
                FirstProductCategory.createFirstProductCategory("스타굿즈"),
                FirstProductCategory.createFirstProductCategory("키덜트"),
                FirstProductCategory.createFirstProductCategory("예술/희귀/수집품"),
                FirstProductCategory.createFirstProductCategory("음반/악기"),
                FirstProductCategory.createFirstProductCategory("도서/티켓/문구"),
                FirstProductCategory.createFirstProductCategory("뷰티/미용"),
                FirstProductCategory.createFirstProductCategory("가구/인테리어"),
                FirstProductCategory.createFirstProductCategory("생활/가공식품"),
                FirstProductCategory.createFirstProductCategory("유아동/출산"),
                FirstProductCategory.createFirstProductCategory("반려동물용품"),
                FirstProductCategory.createFirstProductCategory("기타")
        ));

        List<SecondProductCategory> secondProductCategories = secondProductCategoryRepository.saveAll(Arrays.asList(
                SecondProductCategory.createSecondCategory("패딩/점퍼", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("코트", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("맨투맨", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("후드티/후드집업", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("티셔츠", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("블라우스", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("셔츠", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("바지", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("청바지", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("반바지", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("치마", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("원피스", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("가디건", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("니트/스웨터", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("자켓", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("정장", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("점프수트", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("조끼/베스트", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("트레이닝", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("언더웨어/홈웨어", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("테마/이벤트", firstProductCategories1.get(0)),
                SecondProductCategory.createSecondCategory("패딩/점퍼", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("코트", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("맨투맨", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("후드티/후드집업", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("티셔츠", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("셔츠", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("가디건", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("니트/스웨터", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("바지", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("청바지", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("반바지", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("자켓", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("정장", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("조끼/베스트", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("트레이닝", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("언더웨어/홈웨어", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("테마/이벤트", firstProductCategories1.get(1)),
                SecondProductCategory.createSecondCategory("스니커즈", firstProductCategories1.get(2)),
                SecondProductCategory.createSecondCategory("남성화", firstProductCategories1.get(2)),
                SecondProductCategory.createSecondCategory("여성화", firstProductCategories1.get(2)),
                SecondProductCategory.createSecondCategory("여성가방", firstProductCategories1.get(3)),
                SecondProductCategory.createSecondCategory("남성가방", firstProductCategories1.get(3)),
                SecondProductCategory.createSecondCategory("여행용", firstProductCategories1.get(3)),
                SecondProductCategory.createSecondCategory("시계", firstProductCategories1.get(4)),
                SecondProductCategory.createSecondCategory("주얼리", firstProductCategories1.get(4)),
                SecondProductCategory.createSecondCategory("지갑", firstProductCategories1.get(5)),
                SecondProductCategory.createSecondCategory("벨트", firstProductCategories1.get(5)),
                SecondProductCategory.createSecondCategory("모자", firstProductCategories1.get(5)),
                SecondProductCategory.createSecondCategory("목도리/장갑", firstProductCategories1.get(5)),
                SecondProductCategory.createSecondCategory("스카프/넥타이", firstProductCategories1.get(5)),
                SecondProductCategory.createSecondCategory("안경/선글라스", firstProductCategories1.get(5)),
                SecondProductCategory.createSecondCategory("양말/스타킹", firstProductCategories1.get(5)),
                SecondProductCategory.createSecondCategory("우산/양산", firstProductCategories1.get(5)),
                SecondProductCategory.createSecondCategory("기타 엑세서리", firstProductCategories1.get(5)),
                SecondProductCategory.createSecondCategory("모바일", firstProductCategories1.get(6)),
                SecondProductCategory.createSecondCategory("가전제품", firstProductCategories1.get(6)),
                SecondProductCategory.createSecondCategory("오디오/영상/관련기기", firstProductCategories1.get(6)),
                SecondProductCategory.createSecondCategory("PC/노트북", firstProductCategories1.get(6)),
                SecondProductCategory.createSecondCategory("게임/타이틀", firstProductCategories1.get(6)),
                SecondProductCategory.createSecondCategory("카메라/DSLR", firstProductCategories1.get(6)),
                SecondProductCategory.createSecondCategory("PC부품/저장장치", firstProductCategories1.get(6)),
                SecondProductCategory.createSecondCategory("골프", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("캠핑", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("낚시", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("축구", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("자전거", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("인라인/스케이트보드", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("전동킥보드/전동힐", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("테니스", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("등산/클라이밍", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("헬스/요가/필라테스", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("야구", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("볼링", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("배드민턴", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("탁구", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("농구", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("당구", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("겨울 스포츠", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("수상 스포츠", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("기타 구기 스포츠", firstProductCategories1.get(7)),
                SecondProductCategory.createSecondCategory("국산차", firstProductCategories1.get(8)),
                SecondProductCategory.createSecondCategory("수입차", firstProductCategories1.get(8)),
                SecondProductCategory.createSecondCategory("차량 용품/부품", firstProductCategories1.get(8)),
                SecondProductCategory.createSecondCategory("오토바이/스쿠터", firstProductCategories1.get(8)),
                SecondProductCategory.createSecondCategory("오토바이 용품/부품", firstProductCategories1.get(8)),
                SecondProductCategory.createSecondCategory("산업용 차량/장비", firstProductCategories1.get(8)),
                SecondProductCategory.createSecondCategory("보이그룹", firstProductCategories1.get(9)),
                SecondProductCategory.createSecondCategory("걸그룹", firstProductCategories1.get(9)),
                SecondProductCategory.createSecondCategory("솔로(남)", firstProductCategories1.get(9)),
                SecondProductCategory.createSecondCategory("솔로(여)", firstProductCategories1.get(9)),
                SecondProductCategory.createSecondCategory("배우(남)", firstProductCategories1.get(9)),
                SecondProductCategory.createSecondCategory("배우(여)", firstProductCategories1.get(9)),
                SecondProductCategory.createSecondCategory("방송/예능/캐릭터", firstProductCategories1.get(9)),
                SecondProductCategory.createSecondCategory("피규어/인형", firstProductCategories1.get(10)),
                SecondProductCategory.createSecondCategory("레고/블럭", firstProductCategories1.get(10)),
                SecondProductCategory.createSecondCategory("프라모델", firstProductCategories1.get(10)),
                SecondProductCategory.createSecondCategory("RC/드론", firstProductCategories1.get(10)),
                SecondProductCategory.createSecondCategory("보드게임", firstProductCategories1.get(10)),
                SecondProductCategory.createSecondCategory("서바이벌건", firstProductCategories1.get(10)),
                SecondProductCategory.createSecondCategory("기타(키덜트)", firstProductCategories1.get(10)),
                SecondProductCategory.createSecondCategory("희귀/수집품", firstProductCategories1.get(11)),
                SecondProductCategory.createSecondCategory("골동품", firstProductCategories1.get(11)),
                SecondProductCategory.createSecondCategory("예술작품", firstProductCategories1.get(11)),
                SecondProductCategory.createSecondCategory("CD/DVD/LP", firstProductCategories1.get(12)),
                SecondProductCategory.createSecondCategory("악기", firstProductCategories1.get(12)),
                SecondProductCategory.createSecondCategory("도서", firstProductCategories1.get(13)),
                SecondProductCategory.createSecondCategory("문구", firstProductCategories1.get(13)),
                SecondProductCategory.createSecondCategory("기프티콘/쿠폰", firstProductCategories1.get(13)),
                SecondProductCategory.createSecondCategory("상품권", firstProductCategories1.get(13)),
                SecondProductCategory.createSecondCategory("티켓", firstProductCategories1.get(13)),
                SecondProductCategory.createSecondCategory("스킨케어", firstProductCategories1.get(14)),
                SecondProductCategory.createSecondCategory("색조메이크업", firstProductCategories1.get(14)),
                SecondProductCategory.createSecondCategory("베이스메이크업", firstProductCategories1.get(14)),
                SecondProductCategory.createSecondCategory("바디/헤어케어", firstProductCategories1.get(14)),
                SecondProductCategory.createSecondCategory("향수/아로마", firstProductCategories1.get(14)),
                SecondProductCategory.createSecondCategory("네일아트/케어", firstProductCategories1.get(14)),
                SecondProductCategory.createSecondCategory("미용소품/기기", firstProductCategories1.get(14)),
                SecondProductCategory.createSecondCategory("다이어트/이너뷰티", firstProductCategories1.get(14)),
                SecondProductCategory.createSecondCategory("남성 화장품", firstProductCategories1.get(14)),
                SecondProductCategory.createSecondCategory("가구", firstProductCategories1.get(15)),
                SecondProductCategory.createSecondCategory("인테리어", firstProductCategories1.get(15)),
                SecondProductCategory.createSecondCategory("주방용품", firstProductCategories1.get(16)),
                SecondProductCategory.createSecondCategory("생활용품", firstProductCategories1.get(16)),
                SecondProductCategory.createSecondCategory("식품", firstProductCategories1.get(16)),
                SecondProductCategory.createSecondCategory("산업용품", firstProductCategories1.get(16)),
                SecondProductCategory.createSecondCategory("베이비의류(0~2세)", firstProductCategories1.get(17)),
                SecondProductCategory.createSecondCategory("여의류(3~6세)", firstProductCategories1.get(17)),
                SecondProductCategory.createSecondCategory("여주니어의류(7~세)", firstProductCategories1.get(17)),
                SecondProductCategory.createSecondCategory("남의류(3~6세)", firstProductCategories1.get(17)),
                SecondProductCategory.createSecondCategory("남주니어의류(7~세)", firstProductCategories1.get(17)),
                SecondProductCategory.createSecondCategory("유아용품", firstProductCategories1.get(17)),
                SecondProductCategory.createSecondCategory("출산/임부용품", firstProductCategories1.get(17)),
                SecondProductCategory.createSecondCategory("교육/완구/인형", firstProductCategories1.get(17)),
                SecondProductCategory.createSecondCategory("이유용품/유아식기", firstProductCategories1.get(17)),
                SecondProductCategory.createSecondCategory("강아지 용품", firstProductCategories1.get(18)),
                SecondProductCategory.createSecondCategory("강아지 식품/사료", firstProductCategories1.get(18)),
                SecondProductCategory.createSecondCategory("기타(강아지)", firstProductCategories1.get(18)),
                SecondProductCategory.createSecondCategory("고양이 용품", firstProductCategories1.get(18)),
                SecondProductCategory.createSecondCategory("고양이 식품/사료", firstProductCategories1.get(18)),
                SecondProductCategory.createSecondCategory("기타(고양이)", firstProductCategories1.get(18)),
                SecondProductCategory.createSecondCategory("기타(반려동물 용품)", firstProductCategories1.get(18)),
                SecondProductCategory.createSecondCategory("기타(반려동물 식품/사료)", firstProductCategories1.get(18))
        ));

        thirdProductCategoryRepository.saveAll(Arrays.asList(
                ThirdProductCategory.createThirdCategory("롱패딩", secondProductCategories.get(0)),
                ThirdProductCategory.createThirdCategory("숏패딩", secondProductCategories.get(0)),
                ThirdProductCategory.createThirdCategory("블루종/항공점퍼", secondProductCategories.get(0)),
                ThirdProductCategory.createThirdCategory("기타(패딩/점퍼)", secondProductCategories.get(0)),
                ThirdProductCategory.createThirdCategory("겨울 코트", secondProductCategories.get(1)),
                ThirdProductCategory.createThirdCategory("봄/가을 코트", secondProductCategories.get(1)),
                ThirdProductCategory.createThirdCategory("긴팔 티셔츠", secondProductCategories.get(4)),
                ThirdProductCategory.createThirdCategory("반팔 티셔츠", secondProductCategories.get(4)),
                ThirdProductCategory.createThirdCategory("민소매", secondProductCategories.get(4)),
                ThirdProductCategory.createThirdCategory("긴팔", secondProductCategories.get(5)),
                ThirdProductCategory.createThirdCategory("반팔", secondProductCategories.get(5)),
                ThirdProductCategory.createThirdCategory("민소매/오프숄더", secondProductCategories.get(5)),
                ThirdProductCategory.createThirdCategory("기타(블라우스)", secondProductCategories.get(5)),
                ThirdProductCategory.createThirdCategory("솔리드 셔츠", secondProductCategories.get(6)),
                ThirdProductCategory.createThirdCategory("스트라이프 셔츠", secondProductCategories.get(6)),
                ThirdProductCategory.createThirdCategory("체크 셔츠", secondProductCategories.get(6)),
                ThirdProductCategory.createThirdCategory("청/데님 셔츠", secondProductCategories.get(6)),
                ThirdProductCategory.createThirdCategory("기타(셔츠)", secondProductCategories.get(6)),
                ThirdProductCategory.createThirdCategory("면바지", secondProductCategories.get(7)),
                ThirdProductCategory.createThirdCategory("슬렉스", secondProductCategories.get(7)),
                ThirdProductCategory.createThirdCategory("조거팬츠", secondProductCategories.get(7)),
                ThirdProductCategory.createThirdCategory("레깅스", secondProductCategories.get(7)),
                ThirdProductCategory.createThirdCategory("기타(바지)", secondProductCategories.get(7)),
                ThirdProductCategory.createThirdCategory("롱 스커트", secondProductCategories.get(10)),
                ThirdProductCategory.createThirdCategory("미디 스커트", secondProductCategories.get(10)),
                ThirdProductCategory.createThirdCategory("미니 스커트", secondProductCategories.get(10)),
                ThirdProductCategory.createThirdCategory("롱 원피스", secondProductCategories.get(11)),
                ThirdProductCategory.createThirdCategory("미디 원피스", secondProductCategories.get(11)),
                ThirdProductCategory.createThirdCategory("미니 원피스", secondProductCategories.get(11)),
                ThirdProductCategory.createThirdCategory("가죽", secondProductCategories.get(14)),
                ThirdProductCategory.createThirdCategory("트위드", secondProductCategories.get(14)),
                ThirdProductCategory.createThirdCategory("데님", secondProductCategories.get(14)),
                ThirdProductCategory.createThirdCategory("야상", secondProductCategories.get(14)),
                ThirdProductCategory.createThirdCategory("바람막이", secondProductCategories.get(14)),
                ThirdProductCategory.createThirdCategory("기타(자켓)", secondProductCategories.get(14)),
                ThirdProductCategory.createThirdCategory("자켓", secondProductCategories.get(15)),
                ThirdProductCategory.createThirdCategory("치마", secondProductCategories.get(15)),
                ThirdProductCategory.createThirdCategory("세트", secondProductCategories.get(15)),
                ThirdProductCategory.createThirdCategory("기타(정장)", secondProductCategories.get(15)),
                ThirdProductCategory.createThirdCategory("니트 조끼", secondProductCategories.get(17)),
                ThirdProductCategory.createThirdCategory("브이넥 조끼", secondProductCategories.get(17)),
                ThirdProductCategory.createThirdCategory("청/데님 조끼", secondProductCategories.get(17)),
                ThirdProductCategory.createThirdCategory("패딩 조끼", secondProductCategories.get(17)),
                ThirdProductCategory.createThirdCategory("퍼 조끼", secondProductCategories.get(17)),
                ThirdProductCategory.createThirdCategory("기타(조끼)", secondProductCategories.get(17)),
                ThirdProductCategory.createThirdCategory("상의", secondProductCategories.get(18)),
                ThirdProductCategory.createThirdCategory("하의", secondProductCategories.get(18)),
                ThirdProductCategory.createThirdCategory("세트", secondProductCategories.get(18)),
                ThirdProductCategory.createThirdCategory("기타(트레이닝)", secondProductCategories.get(18)),
                ThirdProductCategory.createThirdCategory("롱패딩", secondProductCategories.get(21)),
                ThirdProductCategory.createThirdCategory("숏패딩", secondProductCategories.get(21)),
                ThirdProductCategory.createThirdCategory("블루종/항공점퍼", secondProductCategories.get(21)),
                ThirdProductCategory.createThirdCategory("기타(패딩/점퍼)", secondProductCategories.get(21)),
                ThirdProductCategory.createThirdCategory("겨울 코트", secondProductCategories.get(22)),
                ThirdProductCategory.createThirdCategory("봄/가을 코트", secondProductCategories.get(22)),
                ThirdProductCategory.createThirdCategory("긴팔 티셔츠", secondProductCategories.get(25)),
                ThirdProductCategory.createThirdCategory("반팔 티셔츠", secondProductCategories.get(25)),
                ThirdProductCategory.createThirdCategory("민소매", secondProductCategories.get(25)),
                ThirdProductCategory.createThirdCategory("솔리드 셔츠", secondProductCategories.get(26)),
                ThirdProductCategory.createThirdCategory("스트라이프 셔츠", secondProductCategories.get(26)),
                ThirdProductCategory.createThirdCategory("체크 셔츠", secondProductCategories.get(26)),
                ThirdProductCategory.createThirdCategory("청/데님 셔츠", secondProductCategories.get(26)),
                ThirdProductCategory.createThirdCategory("기타(셔츠)", secondProductCategories.get(26)),
                ThirdProductCategory.createThirdCategory("면바지", secondProductCategories.get(29)),
                ThirdProductCategory.createThirdCategory("슬렉스", secondProductCategories.get(29)),
                ThirdProductCategory.createThirdCategory("조거팬츠", secondProductCategories.get(29)),
                ThirdProductCategory.createThirdCategory("기타(바지)", secondProductCategories.get(29)),
                ThirdProductCategory.createThirdCategory("가죽", secondProductCategories.get(32)),
                ThirdProductCategory.createThirdCategory("트위드", secondProductCategories.get(32)),
                ThirdProductCategory.createThirdCategory("데님", secondProductCategories.get(32)),
                ThirdProductCategory.createThirdCategory("야상", secondProductCategories.get(32)),
                ThirdProductCategory.createThirdCategory("바람막이", secondProductCategories.get(32)),
                ThirdProductCategory.createThirdCategory("기타(자켓)", secondProductCategories.get(32)),
                ThirdProductCategory.createThirdCategory("자켓", secondProductCategories.get(33)),
                ThirdProductCategory.createThirdCategory("베스트", secondProductCategories.get(33)),
                ThirdProductCategory.createThirdCategory("세트", secondProductCategories.get(33)),
                ThirdProductCategory.createThirdCategory("바지", secondProductCategories.get(33)),
                ThirdProductCategory.createThirdCategory("기타(정장)", secondProductCategories.get(33)),
                ThirdProductCategory.createThirdCategory("니트 조끼", secondProductCategories.get(34)),
                ThirdProductCategory.createThirdCategory("브이넥 조끼", secondProductCategories.get(34)),
                ThirdProductCategory.createThirdCategory("청/데님 조끼", secondProductCategories.get(34)),
                ThirdProductCategory.createThirdCategory("패딩 조끼", secondProductCategories.get(34)),
                ThirdProductCategory.createThirdCategory("기타(조끼)", secondProductCategories.get(34)),
                ThirdProductCategory.createThirdCategory("상의", secondProductCategories.get(35)),
                ThirdProductCategory.createThirdCategory("하의", secondProductCategories.get(35)),
                ThirdProductCategory.createThirdCategory("세트", secondProductCategories.get(35)),
                ThirdProductCategory.createThirdCategory("기타(트레이닝)", secondProductCategories.get(35)),
                ThirdProductCategory.createThirdCategory("샌들/슬리퍼", secondProductCategories.get(39)),
                ThirdProductCategory.createThirdCategory("구두/로퍼", secondProductCategories.get(39)),
                ThirdProductCategory.createThirdCategory("워커/부츠", secondProductCategories.get(39)),
                ThirdProductCategory.createThirdCategory("기타(남성화)", secondProductCategories.get(39)),
                ThirdProductCategory.createThirdCategory("샌들/슬리퍼", secondProductCategories.get(40)),
                ThirdProductCategory.createThirdCategory("구두", secondProductCategories.get(40)),
                ThirdProductCategory.createThirdCategory("단화/플랫슈즈", secondProductCategories.get(40)),
                ThirdProductCategory.createThirdCategory("워커/부츠", secondProductCategories.get(40)),
                ThirdProductCategory.createThirdCategory("기타(여성화)", secondProductCategories.get(40)),
                ThirdProductCategory.createThirdCategory("클러치백", secondProductCategories.get(41)),
                ThirdProductCategory.createThirdCategory("숄더백", secondProductCategories.get(41)),
                ThirdProductCategory.createThirdCategory("크로스백", secondProductCategories.get(41)),
                ThirdProductCategory.createThirdCategory("토트백", secondProductCategories.get(41)),
                ThirdProductCategory.createThirdCategory("백백", secondProductCategories.get(41)),
                ThirdProductCategory.createThirdCategory("기타(가방)", secondProductCategories.get(41)),
                ThirdProductCategory.createThirdCategory("클러치", secondProductCategories.get(42)),
                ThirdProductCategory.createThirdCategory("숄더백", secondProductCategories.get(42)),
                ThirdProductCategory.createThirdCategory("크로스백", secondProductCategories.get(42)),
                ThirdProductCategory.createThirdCategory("브러프케이스", secondProductCategories.get(42)),
                ThirdProductCategory.createThirdCategory("백백", secondProductCategories.get(42)),
                ThirdProductCategory.createThirdCategory("남성시계", secondProductCategories.get(43)),
                ThirdProductCategory.createThirdCategory("여성시계", secondProductCategories.get(43)),
                ThirdProductCategory.createThirdCategory("기타(시계)", secondProductCategories.get(43)),
                ThirdProductCategory.createThirdCategory("귀걸이/피어싱", secondProductCategories.get(44)),
                ThirdProductCategory.createThirdCategory("목걸이/팬던트", secondProductCategories.get(44)),
                ThirdProductCategory.createThirdCategory("팔찌/발찌", secondProductCategories.get(44)),
                ThirdProductCategory.createThirdCategory("반지", secondProductCategories.get(44)),
                ThirdProductCategory.createThirdCategory("기타(주얼리)", secondProductCategories.get(44)),
                ThirdProductCategory.createThirdCategory("남성지갑", secondProductCategories.get(45)),
                ThirdProductCategory.createThirdCategory("여성지갑", secondProductCategories.get(45)),
                ThirdProductCategory.createThirdCategory("기타(지갑)", secondProductCategories.get(45)),
                ThirdProductCategory.createThirdCategory("볼캡", secondProductCategories.get(47)),
                ThirdProductCategory.createThirdCategory("버킷", secondProductCategories.get(47)),
                ThirdProductCategory.createThirdCategory("스냅백", secondProductCategories.get(47)),
                ThirdProductCategory.createThirdCategory("비니", secondProductCategories.get(47)),
                ThirdProductCategory.createThirdCategory("기타(모자)", secondProductCategories.get(47)),
                ThirdProductCategory.createThirdCategory("목도리", secondProductCategories.get(48)),
                ThirdProductCategory.createThirdCategory("장갑", secondProductCategories.get(48)),
                ThirdProductCategory.createThirdCategory("스카프", secondProductCategories.get(49)),
                ThirdProductCategory.createThirdCategory("넥타이", secondProductCategories.get(49)),
                ThirdProductCategory.createThirdCategory("선글라스", secondProductCategories.get(50)),
                ThirdProductCategory.createThirdCategory("안경", secondProductCategories.get(50)),
                ThirdProductCategory.createThirdCategory("양말", secondProductCategories.get(51)),
                ThirdProductCategory.createThirdCategory("스타킹", secondProductCategories.get(51)),
                ThirdProductCategory.createThirdCategory("스마트폰", secondProductCategories.get(54)),
                ThirdProductCategory.createThirdCategory("태블릿", secondProductCategories.get(54)),
                ThirdProductCategory.createThirdCategory("웨어러블(워치)", secondProductCategories.get(54)),
                ThirdProductCategory.createThirdCategory("일반폰(피처폰)", secondProductCategories.get(54)),
                ThirdProductCategory.createThirdCategory("케이스/보호필름/엑세서리", secondProductCategories.get(54)),
                ThirdProductCategory.createThirdCategory("케이블/충전기/주변기기", secondProductCategories.get(54)),
                ThirdProductCategory.createThirdCategory("기타(모바일)", secondProductCategories.get(54)),
                ThirdProductCategory.createThirdCategory("생활가전", secondProductCategories.get(55)),
                ThirdProductCategory.createThirdCategory("대형가전", secondProductCategories.get(55)),
                ThirdProductCategory.createThirdCategory("TV", secondProductCategories.get(55)),
                ThirdProductCategory.createThirdCategory("미용가전", secondProductCategories.get(55)),
                ThirdProductCategory.createThirdCategory("사무기기(복사기/팩스 등)", secondProductCategories.get(55)),
                ThirdProductCategory.createThirdCategory("기타(가전제품)", secondProductCategories.get(55)),
                ThirdProductCategory.createThirdCategory("이어폰/헤드폰", secondProductCategories.get(56)),
                ThirdProductCategory.createThirdCategory("스피커/엠프", secondProductCategories.get(56)),
                ThirdProductCategory.createThirdCategory("아이팟/MP3/PMP", secondProductCategories.get(56)),
                ThirdProductCategory.createThirdCategory("비디오/프로젝터", secondProductCategories.get(56)),
                ThirdProductCategory.createThirdCategory("오디오/홈시어터", secondProductCategories.get(56)),
                ThirdProductCategory.createThirdCategory("기타(오디오/영상/관련기기)", secondProductCategories.get(56)),
                ThirdProductCategory.createThirdCategory("데스크탑", secondProductCategories.get(57)),
                ThirdProductCategory.createThirdCategory("노트북/넷북", secondProductCategories.get(57)),
                ThirdProductCategory.createThirdCategory("모니터", secondProductCategories.get(57)),
                ThirdProductCategory.createThirdCategory("PC주변기기(키보드/마우스)", secondProductCategories.get(57)),
                ThirdProductCategory.createThirdCategory("노트북 가방/엑세서리", secondProductCategories.get(57)),
                ThirdProductCategory.createThirdCategory("기타(PC/노트북)", secondProductCategories.get(57)),
                ThirdProductCategory.createThirdCategory("닌텐도/NDS/Wii", secondProductCategories.get(58)),
                ThirdProductCategory.createThirdCategory("소니/플레이스테이션", secondProductCategories.get(58)),
                ThirdProductCategory.createThirdCategory("XBOX", secondProductCategories.get(58)),
                ThirdProductCategory.createThirdCategory("PC게임", secondProductCategories.get(58)),
                ThirdProductCategory.createThirdCategory("기타(게임/타이틀)", secondProductCategories.get(58)),
                ThirdProductCategory.createThirdCategory("필름카메라/중형카메라", secondProductCategories.get(59)),
                ThirdProductCategory.createThirdCategory("DSLR/미러리스", secondProductCategories.get(59)),
                ThirdProductCategory.createThirdCategory("랜즈/필터/컨버터", secondProductCategories.get(59)),
                ThirdProductCategory.createThirdCategory("일반디카/토이카메라", secondProductCategories.get(59)),
                ThirdProductCategory.createThirdCategory("삼각대/플래시/조명", secondProductCategories.get(59)),
                ThirdProductCategory.createThirdCategory("디지털 캠코더", secondProductCategories.get(59)),
                ThirdProductCategory.createThirdCategory("메모리/배터리/가방", secondProductCategories.get(59)),
                ThirdProductCategory.createThirdCategory("기타(카메라)", secondProductCategories.get(59)),
                ThirdProductCategory.createThirdCategory("메모리/VGA", secondProductCategories.get(60)),
                ThirdProductCategory.createThirdCategory("CPU/메인보드", secondProductCategories.get(60)),
                ThirdProductCategory.createThirdCategory("HDD/ODD/SSD", secondProductCategories.get(60)),
                ThirdProductCategory.createThirdCategory("USB/케이블/스피커", secondProductCategories.get(60)),
                ThirdProductCategory.createThirdCategory("복합기/프린터", secondProductCategories.get(60)),
                ThirdProductCategory.createThirdCategory("네트워크장비", secondProductCategories.get(60)),
                ThirdProductCategory.createThirdCategory("쿨러/파워서플라이", secondProductCategories.get(60)),
                ThirdProductCategory.createThirdCategory("소모품", secondProductCategories.get(60)),
                ThirdProductCategory.createThirdCategory("골프 채", secondProductCategories.get(61)),
                ThirdProductCategory.createThirdCategory("골프 남성 의류", secondProductCategories.get(61)),
                ThirdProductCategory.createThirdCategory("골프 여성 의류", secondProductCategories.get(61)),
                ThirdProductCategory.createThirdCategory("기타 골프 의류", secondProductCategories.get(61)),
                ThirdProductCategory.createThirdCategory("텐트/그늘막", secondProductCategories.get(62)),
                ThirdProductCategory.createThirdCategory("캠핑용품", secondProductCategories.get(62)),
                ThirdProductCategory.createThirdCategory("캠핑 취사용품", secondProductCategories.get(62)),
                ThirdProductCategory.createThirdCategory("기타 캠핑 용품", secondProductCategories.get(62)),
                ThirdProductCategory.createThirdCategory("공통 낚시 장비", secondProductCategories.get(63)),
                ThirdProductCategory.createThirdCategory("바다 낚시", secondProductCategories.get(63)),
                ThirdProductCategory.createThirdCategory("민물 낚시", secondProductCategories.get(63)),
                ThirdProductCategory.createThirdCategory("루어/플라이 낚시", secondProductCategories.get(63)),
                ThirdProductCategory.createThirdCategory("낚시 의류 및 기타 용품", secondProductCategories.get(63)),
                ThirdProductCategory.createThirdCategory("축구 의류/잡화", secondProductCategories.get(64)),
                ThirdProductCategory.createThirdCategory("축구 용품", secondProductCategories.get(64)),
                ThirdProductCategory.createThirdCategory("자전거 의류 및 엑세서리", secondProductCategories.get(65)),
                ThirdProductCategory.createThirdCategory("클래식/픽시", secondProductCategories.get(65)),
                ThirdProductCategory.createThirdCategory("로드/BMX", secondProductCategories.get(65)),
                ThirdProductCategory.createThirdCategory("MTB/산악", secondProductCategories.get(65)),
                ThirdProductCategory.createThirdCategory("미니벨로/접이식", secondProductCategories.get(65)),
                ThirdProductCategory.createThirdCategory("전동/하이브리드", secondProductCategories.get(65)),
                ThirdProductCategory.createThirdCategory("기타 자전거", secondProductCategories.get(65)),
                ThirdProductCategory.createThirdCategory("자전거 부품", secondProductCategories.get(65)),
                ThirdProductCategory.createThirdCategory("남성 등산복", secondProductCategories.get(69)),
                ThirdProductCategory.createThirdCategory("여성 등산복", secondProductCategories.get(69)),
                ThirdProductCategory.createThirdCategory("등산화/트레킹화", secondProductCategories.get(69)),
                ThirdProductCategory.createThirdCategory("등산 가방", secondProductCategories.get(69)),
                ThirdProductCategory.createThirdCategory("암벽/클라이밍", secondProductCategories.get(69)),
                ThirdProductCategory.createThirdCategory("기타 등상 용품", secondProductCategories.get(69)),
                ThirdProductCategory.createThirdCategory("헬스/요가/필라테스 장비", secondProductCategories.get(70)),
                ThirdProductCategory.createThirdCategory("헬스/요가/필라테스 의류", secondProductCategories.get(70)),
                ThirdProductCategory.createThirdCategory("기타 용품", secondProductCategories.get(70)),
                ThirdProductCategory.createThirdCategory("야구 의류/잡화", secondProductCategories.get(71)),
                ThirdProductCategory.createThirdCategory("야구 용품", secondProductCategories.get(71)),
                ThirdProductCategory.createThirdCategory("농구 의류/잡화", secondProductCategories.get(75)),
                ThirdProductCategory.createThirdCategory("농구 용품", secondProductCategories.get(75)),
                ThirdProductCategory.createThirdCategory("스키/보드 의류 및 잡화", secondProductCategories.get(77)),
                ThirdProductCategory.createThirdCategory("스노우보드 장비", secondProductCategories.get(77)),
                ThirdProductCategory.createThirdCategory("스키 장비", secondProductCategories.get(77)),
                ThirdProductCategory.createThirdCategory("기타 겨울 스포츠", secondProductCategories.get(77)),
                ThirdProductCategory.createThirdCategory("수영/물놀이 용품", secondProductCategories.get(78)),
                ThirdProductCategory.createThirdCategory("남성 수영복/래쉬가드", secondProductCategories.get(78)),
                ThirdProductCategory.createThirdCategory("여성 수영복/래쉬가드", secondProductCategories.get(78)),
                ThirdProductCategory.createThirdCategory("기타(수영복)", secondProductCategories.get(78)),
                ThirdProductCategory.createThirdCategory("서핑", secondProductCategories.get(78)),
                ThirdProductCategory.createThirdCategory("요트", secondProductCategories.get(78)),
                ThirdProductCategory.createThirdCategory("기타 수상 스포츠", secondProductCategories.get(78)),
                ThirdProductCategory.createThirdCategory("경차/소형차", secondProductCategories.get(80)),
                ThirdProductCategory.createThirdCategory("준/중형차", secondProductCategories.get(80)),
                ThirdProductCategory.createThirdCategory("준/대형차", secondProductCategories.get(80)),
                ThirdProductCategory.createThirdCategory("SUV/RV", secondProductCategories.get(80)),
                ThirdProductCategory.createThirdCategory("벤/승합차", secondProductCategories.get(80)),
                ThirdProductCategory.createThirdCategory("버스/화물차", secondProductCategories.get(80)),
                ThirdProductCategory.createThirdCategory("스포츠카", secondProductCategories.get(80)),
                ThirdProductCategory.createThirdCategory("기타(국산차)", secondProductCategories.get(80)),
                ThirdProductCategory.createThirdCategory("경차/소형차", secondProductCategories.get(81)),
                ThirdProductCategory.createThirdCategory("준/중형차", secondProductCategories.get(81)),
                ThirdProductCategory.createThirdCategory("준/대형차", secondProductCategories.get(81)),
                ThirdProductCategory.createThirdCategory("SUV/RV", secondProductCategories.get(81)),
                ThirdProductCategory.createThirdCategory("벤/승합차", secondProductCategories.get(81)),
                ThirdProductCategory.createThirdCategory("버스/화물차", secondProductCategories.get(81)),
                ThirdProductCategory.createThirdCategory("스포츠카", secondProductCategories.get(81)),
                ThirdProductCategory.createThirdCategory("기타(수입차)", secondProductCategories.get(81)),
                ThirdProductCategory.createThirdCategory("타이어/휠", secondProductCategories.get(82)),
                ThirdProductCategory.createThirdCategory("차량 부품", secondProductCategories.get(82)),
                ThirdProductCategory.createThirdCategory("차량/튜닝 용품", secondProductCategories.get(82)),
                ThirdProductCategory.createThirdCategory("네비게이션/블랙박스", secondProductCategories.get(82)),
                ThirdProductCategory.createThirdCategory("카오디오/영상", secondProductCategories.get(82)),
                ThirdProductCategory.createThirdCategory("오토바이(125cc 이하)", secondProductCategories.get(83)),
                ThirdProductCategory.createThirdCategory("오토바이(125cc 초과)", secondProductCategories.get(83)),
                ThirdProductCategory.createThirdCategory("라이더 용품", secondProductCategories.get(84)),
                ThirdProductCategory.createThirdCategory("오토바이 용품", secondProductCategories.get(84)),
                ThirdProductCategory.createThirdCategory("오토바이/튜닝 용품", secondProductCategories.get(84)),
                ThirdProductCategory.createThirdCategory("기타(오토바이 용품/부품)", secondProductCategories.get(84)),
                ThirdProductCategory.createThirdCategory("굴삭기/지게차", secondProductCategories.get(85)),
                ThirdProductCategory.createThirdCategory("농기계/경운기", secondProductCategories.get(85)),
                ThirdProductCategory.createThirdCategory("음반/영상물", secondProductCategories.get(86)),
                ThirdProductCategory.createThirdCategory("팬시/포트카드", secondProductCategories.get(86)),
                ThirdProductCategory.createThirdCategory("포스터/화보", secondProductCategories.get(86)),
                ThirdProductCategory.createThirdCategory("인형/피규어", secondProductCategories.get(86)),
                ThirdProductCategory.createThirdCategory("응원도구", secondProductCategories.get(86)),
                ThirdProductCategory.createThirdCategory("의류/패션잡화", secondProductCategories.get(86)),
                ThirdProductCategory.createThirdCategory("기타(보이그룹)", secondProductCategories.get(86)),
                ThirdProductCategory.createThirdCategory("음반/영상물", secondProductCategories.get(87)),
                ThirdProductCategory.createThirdCategory("팬시/포트카드", secondProductCategories.get(87)),
                ThirdProductCategory.createThirdCategory("포스터/화보", secondProductCategories.get(87)),
                ThirdProductCategory.createThirdCategory("인형/피규어", secondProductCategories.get(87)),
                ThirdProductCategory.createThirdCategory("응원도구", secondProductCategories.get(87)),
                ThirdProductCategory.createThirdCategory("의류/패션잡화", secondProductCategories.get(87)),
                ThirdProductCategory.createThirdCategory("기타(걸그룹)", secondProductCategories.get(87)),
                ThirdProductCategory.createThirdCategory("음반/영상물", secondProductCategories.get(88)),
                ThirdProductCategory.createThirdCategory("팬시/포트카드", secondProductCategories.get(88)),
                ThirdProductCategory.createThirdCategory("포스터/화보", secondProductCategories.get(88)),
                ThirdProductCategory.createThirdCategory("인형/피규어", secondProductCategories.get(88)),
                ThirdProductCategory.createThirdCategory("응원도구", secondProductCategories.get(88)),
                ThirdProductCategory.createThirdCategory("의류/패션잡화", secondProductCategories.get(88)),
                ThirdProductCategory.createThirdCategory("기타(솔로-남)", secondProductCategories.get(88)),
                ThirdProductCategory.createThirdCategory("음반/영상물", secondProductCategories.get(89)),
                ThirdProductCategory.createThirdCategory("팬시/포트카드", secondProductCategories.get(89)),
                ThirdProductCategory.createThirdCategory("포스터/화보", secondProductCategories.get(89)),
                ThirdProductCategory.createThirdCategory("인형/피규어", secondProductCategories.get(89)),
                ThirdProductCategory.createThirdCategory("응원도구", secondProductCategories.get(89)),
                ThirdProductCategory.createThirdCategory("의류/패션잡화", secondProductCategories.get(89)),
                ThirdProductCategory.createThirdCategory("기타(솔로-여)", secondProductCategories.get(89)),
                ThirdProductCategory.createThirdCategory("음반/영상물", secondProductCategories.get(90)),
                ThirdProductCategory.createThirdCategory("팬시/포트카드", secondProductCategories.get(90)),
                ThirdProductCategory.createThirdCategory("포스터/화보", secondProductCategories.get(90)),
                ThirdProductCategory.createThirdCategory("인형/피규어", secondProductCategories.get(90)),
                ThirdProductCategory.createThirdCategory("응원도구", secondProductCategories.get(90)),
                ThirdProductCategory.createThirdCategory("의류/패션잡화", secondProductCategories.get(90)),
                ThirdProductCategory.createThirdCategory("기타(배우-남)", secondProductCategories.get(90)),
                ThirdProductCategory.createThirdCategory("음반/영상물", secondProductCategories.get(91)),
                ThirdProductCategory.createThirdCategory("팬시/포트카드", secondProductCategories.get(91)),
                ThirdProductCategory.createThirdCategory("포스터/화보", secondProductCategories.get(91)),
                ThirdProductCategory.createThirdCategory("인형/피규어", secondProductCategories.get(91)),
                ThirdProductCategory.createThirdCategory("응원도구", secondProductCategories.get(91)),
                ThirdProductCategory.createThirdCategory("의류/패션잡화", secondProductCategories.get(91)),
                ThirdProductCategory.createThirdCategory("기타(배우-여)", secondProductCategories.get(91)),
                ThirdProductCategory.createThirdCategory("음반/영상물", secondProductCategories.get(92)),
                ThirdProductCategory.createThirdCategory("팬시/포트카드", secondProductCategories.get(92)),
                ThirdProductCategory.createThirdCategory("포스터/화보", secondProductCategories.get(92)),
                ThirdProductCategory.createThirdCategory("인형/피규어", secondProductCategories.get(92)),
                ThirdProductCategory.createThirdCategory("응원도구", secondProductCategories.get(92)),
                ThirdProductCategory.createThirdCategory("의류/패션잡화", secondProductCategories.get(92)),
                ThirdProductCategory.createThirdCategory("기타(방송인)", secondProductCategories.get(92)),
                ThirdProductCategory.createThirdCategory("관악기", secondProductCategories.get(104)),
                ThirdProductCategory.createThirdCategory("현악기", secondProductCategories.get(104)),
                ThirdProductCategory.createThirdCategory("타악기", secondProductCategories.get(104)),
                ThirdProductCategory.createThirdCategory("건반악기", secondProductCategories.get(104)),
                ThirdProductCategory.createThirdCategory("전자악기", secondProductCategories.get(104)),
                ThirdProductCategory.createThirdCategory("악기용품", secondProductCategories.get(104)),
                ThirdProductCategory.createThirdCategory("기타(음반/악기)", secondProductCategories.get(104)),
                ThirdProductCategory.createThirdCategory("시/소설", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("자기계발", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("교양/인문", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("경제/경영", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("학습/사전/참고서", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("아동/어린이", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("만화", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("예술/디자인", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("여행/취미/레저/건강", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("사회/정치/법", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("과학/IT", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("간행물", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("기타(도서)", secondProductCategories.get(105)),
                ThirdProductCategory.createThirdCategory("학습도구/문구/필기류", secondProductCategories.get(106)),
                ThirdProductCategory.createThirdCategory("미술/화방용품", secondProductCategories.get(106)),
                ThirdProductCategory.createThirdCategory("치킨/피자/햄버거", secondProductCategories.get(107)),
                ThirdProductCategory.createThirdCategory("베이커리/도넛/아이스크림", secondProductCategories.get(107)),
                ThirdProductCategory.createThirdCategory("커피(음료)", secondProductCategories.get(107)),
                ThirdProductCategory.createThirdCategory("편의점", secondProductCategories.get(107)),
                ThirdProductCategory.createThirdCategory("기타(기프티콘/쿠폰)", secondProductCategories.get(107)),
                ThirdProductCategory.createThirdCategory("문화/도서", secondProductCategories.get(108)),
                ThirdProductCategory.createThirdCategory("백화점", secondProductCategories.get(108)),
                ThirdProductCategory.createThirdCategory("외식", secondProductCategories.get(108)),
                ThirdProductCategory.createThirdCategory("기타(상품권)", secondProductCategories.get(108)),
                ThirdProductCategory.createThirdCategory("뮤지컬/연극", secondProductCategories.get(109)),
                ThirdProductCategory.createThirdCategory("콘서트", secondProductCategories.get(109)),
                ThirdProductCategory.createThirdCategory("영화(예매/관람권)", secondProductCategories.get(109)),
                ThirdProductCategory.createThirdCategory("여행/숙박/렌트", secondProductCategories.get(109)),
                ThirdProductCategory.createThirdCategory("테마파크", secondProductCategories.get(109)),
                ThirdProductCategory.createThirdCategory("스포츠/레저", secondProductCategories.get(109)),
                ThirdProductCategory.createThirdCategory("공연/전시/행사", secondProductCategories.get(109)),
                ThirdProductCategory.createThirdCategory("기타(티켓)", secondProductCategories.get(109)),
                ThirdProductCategory.createThirdCategory("클랜징/스크럼", secondProductCategories.get(110)),
                ThirdProductCategory.createThirdCategory("스킨/토너/미스트", secondProductCategories.get(110)),
                ThirdProductCategory.createThirdCategory("로션/에멀젼", secondProductCategories.get(110)),
                ThirdProductCategory.createThirdCategory("에센스/크림", secondProductCategories.get(110)),
                ThirdProductCategory.createThirdCategory("팩/마스크", secondProductCategories.get(110)),
                ThirdProductCategory.createThirdCategory("씬케어", secondProductCategories.get(110)),
                ThirdProductCategory.createThirdCategory("기타(스킨케어)", secondProductCategories.get(110)),
                ThirdProductCategory.createThirdCategory("아이라이너/브로우", secondProductCategories.get(111)),
                ThirdProductCategory.createThirdCategory("마이섀도우", secondProductCategories.get(111)),
                ThirdProductCategory.createThirdCategory("마스카라", secondProductCategories.get(111)),
                ThirdProductCategory.createThirdCategory("립틴트", secondProductCategories.get(111)),
                ThirdProductCategory.createThirdCategory("립밤/립글로즈", secondProductCategories.get(111)),
                ThirdProductCategory.createThirdCategory("립스틱", secondProductCategories.get(111)),
                ThirdProductCategory.createThirdCategory("치크/블러셔", secondProductCategories.get(111)),
                ThirdProductCategory.createThirdCategory("메이크업베이스", secondProductCategories.get(112)),
                ThirdProductCategory.createThirdCategory("BB/CC크림", secondProductCategories.get(112)),
                ThirdProductCategory.createThirdCategory("쿠션팩트", secondProductCategories.get(112)),
                ThirdProductCategory.createThirdCategory("파운데이션", secondProductCategories.get(112)),
                ThirdProductCategory.createThirdCategory("파우더/팩트", secondProductCategories.get(112)),
                ThirdProductCategory.createThirdCategory("프라이머/컨실러", secondProductCategories.get(112)),
                ThirdProductCategory.createThirdCategory("샴푸/린스", secondProductCategories.get(113)),
                ThirdProductCategory.createThirdCategory("헤어에센스/트리트먼트", secondProductCategories.get(113)),
                ThirdProductCategory.createThirdCategory("헤어스타일링", secondProductCategories.get(113)),
                ThirdProductCategory.createThirdCategory("헤어컬러(염색)", secondProductCategories.get(113)),
                ThirdProductCategory.createThirdCategory("발모제/탈모관련", secondProductCategories.get(113)),
                ThirdProductCategory.createThirdCategory("바디클랜저/로션", secondProductCategories.get(113)),
                ThirdProductCategory.createThirdCategory("핸드/풋 케어", secondProductCategories.get(113)),
                ThirdProductCategory.createThirdCategory("기타(헤어/바디)", secondProductCategories.get(113)),
                ThirdProductCategory.createThirdCategory("여성 향수", secondProductCategories.get(114)),
                ThirdProductCategory.createThirdCategory("남성 향수", secondProductCategories.get(114)),
                ThirdProductCategory.createThirdCategory("남여공용 향수", secondProductCategories.get(114)),
                ThirdProductCategory.createThirdCategory("기타(향수/아로마)", secondProductCategories.get(114)),
                ThirdProductCategory.createThirdCategory("네일아트/스티커", secondProductCategories.get(115)),
                ThirdProductCategory.createThirdCategory("매니큐어/페디큐어", secondProductCategories.get(115)),
                ThirdProductCategory.createThirdCategory("네일케어도구", secondProductCategories.get(115)),
                ThirdProductCategory.createThirdCategory("네일리무버", secondProductCategories.get(115)),
                ThirdProductCategory.createThirdCategory("기타(네일아트/케어)", secondProductCategories.get(115)),
                ThirdProductCategory.createThirdCategory("미용가전(고데기)", secondProductCategories.get(116)),
                ThirdProductCategory.createThirdCategory("피부케어기기", secondProductCategories.get(116)),
                ThirdProductCategory.createThirdCategory("뷰티소품(퍼프/거울)", secondProductCategories.get(116)),
                ThirdProductCategory.createThirdCategory("메이크업 브러쉬", secondProductCategories.get(116)),
                ThirdProductCategory.createThirdCategory("화장품 파우치/정리함", secondProductCategories.get(116)),
                ThirdProductCategory.createThirdCategory("기타(이미용품)", secondProductCategories.get(116)),
                ThirdProductCategory.createThirdCategory("스킨/로션", secondProductCategories.get(118)),
                ThirdProductCategory.createThirdCategory("클랜징/마스크", secondProductCategories.get(118)),
                ThirdProductCategory.createThirdCategory("에센스/크림", secondProductCategories.get(118)),
                ThirdProductCategory.createThirdCategory("BB크림", secondProductCategories.get(118)),
                ThirdProductCategory.createThirdCategory("선케어", secondProductCategories.get(118)),
                ThirdProductCategory.createThirdCategory("왁스", secondProductCategories.get(118)),
                ThirdProductCategory.createThirdCategory("올인원", secondProductCategories.get(118)),
                ThirdProductCategory.createThirdCategory("세트", secondProductCategories.get(118)),
                ThirdProductCategory.createThirdCategory("기타(남성화장품)", secondProductCategories.get(118)),
                ThirdProductCategory.createThirdCategory("소품", secondProductCategories.get(119)),
                ThirdProductCategory.createThirdCategory("꽃/원예", secondProductCategories.get(119)),
                ThirdProductCategory.createThirdCategory("수공예품", secondProductCategories.get(119)),
                ThirdProductCategory.createThirdCategory("침실가구", secondProductCategories.get(120)),
                ThirdProductCategory.createThirdCategory("거실가구", secondProductCategories.get(120)),
                ThirdProductCategory.createThirdCategory("침구", secondProductCategories.get(120)),
                ThirdProductCategory.createThirdCategory("사무용가구", secondProductCategories.get(120)),
                ThirdProductCategory.createThirdCategory("냄비/프라이팬", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("주전자/티포트", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("칼/도마", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("그릇/홈세트", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("수저/커트러리", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("머그잔/컵", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("조리도구", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("제과/제빵", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("커피용품", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("텀블러/물병", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("보관/밀폐용기", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("주방수납", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("업소용품/기기", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("기타(주방용품)", secondProductCategories.get(121)),
                ThirdProductCategory.createThirdCategory("DIY/리폼용품/공구", secondProductCategories.get(122)),
                ThirdProductCategory.createThirdCategory("욕실 용품", secondProductCategories.get(122)),
                ThirdProductCategory.createThirdCategory("기타(생활용품)", secondProductCategories.get(122)),
                ThirdProductCategory.createThirdCategory("건강식품", secondProductCategories.get(123)),
                ThirdProductCategory.createThirdCategory("가공식품", secondProductCategories.get(123)),
                ThirdProductCategory.createThirdCategory("농수축산물", secondProductCategories.get(123)),
                ThirdProductCategory.createThirdCategory("기타(식품)", secondProductCategories.get(123)),
                ThirdProductCategory.createThirdCategory("드릴/전동공구", secondProductCategories.get(124)),
                ThirdProductCategory.createThirdCategory("공구/공구함", secondProductCategories.get(124)),
                ThirdProductCategory.createThirdCategory("산업용품/자재", secondProductCategories.get(124)),
                ThirdProductCategory.createThirdCategory("에어/유압공구", secondProductCategories.get(124)),
                ThirdProductCategory.createThirdCategory("공장기계/용접/가스", secondProductCategories.get(124)),
                ThirdProductCategory.createThirdCategory("측정/계측/레벨", secondProductCategories.get(124)),
                ThirdProductCategory.createThirdCategory("기타(산업용품)", secondProductCategories.get(124)),
                ThirdProductCategory.createThirdCategory("원피스", secondProductCategories.get(125)),
                ThirdProductCategory.createThirdCategory("우주복/슈트", secondProductCategories.get(125)),
                ThirdProductCategory.createThirdCategory("유아상의", secondProductCategories.get(125)),
                ThirdProductCategory.createThirdCategory("자켓/점퍼", secondProductCategories.get(125)),
                ThirdProductCategory.createThirdCategory("유아하의", secondProductCategories.get(125)),
                ThirdProductCategory.createThirdCategory("정장/드레스", secondProductCategories.get(125)),
                ThirdProductCategory.createThirdCategory("베이비수영복", secondProductCategories.get(125)),
                ThirdProductCategory.createThirdCategory("유아내의/속옷", secondProductCategories.get(125)),
                ThirdProductCategory.createThirdCategory("기타(베이비의류)", secondProductCategories.get(125)),
                ThirdProductCategory.createThirdCategory("티셔츠", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("블라우스/남방", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("가디건/조끼", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("니트/스웨터", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("자켓/점퍼", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("코트/정장", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("원피스", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("상하복세트", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("팬츠", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("스커트/치마", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("수영복", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("속옷/잠옷", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("기타(여아의류)", secondProductCategories.get(126)),
                ThirdProductCategory.createThirdCategory("티셔츠", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("블라우스/남방", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("가디건/조끼", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("니트/스웨터", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("자켓/점퍼", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("코트/정장", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("원피스", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("상하복세트", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("팬츠", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("스커트/치마", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("수영복", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("속옷/잠옷", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("기타(여주니어의류)", secondProductCategories.get(127)),
                ThirdProductCategory.createThirdCategory("티셔츠", secondProductCategories.get(128)),
                ThirdProductCategory.createThirdCategory("셔츠/남방", secondProductCategories.get(128)),
                ThirdProductCategory.createThirdCategory("가디건/조끼", secondProductCategories.get(128)),
                ThirdProductCategory.createThirdCategory("니트/스웨터", secondProductCategories.get(128)),
                ThirdProductCategory.createThirdCategory("자켓/점퍼", secondProductCategories.get(128)),
                ThirdProductCategory.createThirdCategory("코트/정장", secondProductCategories.get(128)),
                ThirdProductCategory.createThirdCategory("상하복세트", secondProductCategories.get(128)),
                ThirdProductCategory.createThirdCategory("팬츠", secondProductCategories.get(128)),
                ThirdProductCategory.createThirdCategory("수영복", secondProductCategories.get(128)),
                ThirdProductCategory.createThirdCategory("속옷/잠옷", secondProductCategories.get(128)),
                ThirdProductCategory.createThirdCategory("기타(남아의류)", secondProductCategories.get(128)),
                ThirdProductCategory.createThirdCategory("티셔츠", secondProductCategories.get(129)),
                ThirdProductCategory.createThirdCategory("셔츠/남방", secondProductCategories.get(129)),
                ThirdProductCategory.createThirdCategory("가디건/조끼", secondProductCategories.get(129)),
                ThirdProductCategory.createThirdCategory("니트/스웨터", secondProductCategories.get(129)),
                ThirdProductCategory.createThirdCategory("자켓/점퍼", secondProductCategories.get(129)),
                ThirdProductCategory.createThirdCategory("코트/정장", secondProductCategories.get(129)),
                ThirdProductCategory.createThirdCategory("상하복세트", secondProductCategories.get(129)),
                ThirdProductCategory.createThirdCategory("팬츠", secondProductCategories.get(129)),
                ThirdProductCategory.createThirdCategory("수영복", secondProductCategories.get(129)),
                ThirdProductCategory.createThirdCategory("속옷/잠옷", secondProductCategories.get(129)),
                ThirdProductCategory.createThirdCategory("기타(남아의류)", secondProductCategories.get(129)),
                ThirdProductCategory.createThirdCategory("신발", secondProductCategories.get(130)),
                ThirdProductCategory.createThirdCategory("가방", secondProductCategories.get(130)),
                ThirdProductCategory.createThirdCategory("모자", secondProductCategories.get(130)),
                ThirdProductCategory.createThirdCategory("시계/액세서리", secondProductCategories.get(130)),
                ThirdProductCategory.createThirdCategory("양말", secondProductCategories.get(130)),
                ThirdProductCategory.createThirdCategory("인형(유아용)", secondProductCategories.get(131)),
                ThirdProductCategory.createThirdCategory("교육완구", secondProductCategories.get(131)),
                ThirdProductCategory.createThirdCategory("도서/CD/DVD", secondProductCategories.get(131)),
                ThirdProductCategory.createThirdCategory("퍼즐/블록", secondProductCategories.get(131)),
                ThirdProductCategory.createThirdCategory("자전거/승용완구", secondProductCategories.get(131)),
                ThirdProductCategory.createThirdCategory("스포츠완구", secondProductCategories.get(131)),
                ThirdProductCategory.createThirdCategory("물놀이용품", secondProductCategories.get(131)),
                ThirdProductCategory.createThirdCategory("볼텐트/놀이터", secondProductCategories.get(131)),
                ThirdProductCategory.createThirdCategory("신생아완구", secondProductCategories.get(131)),
                ThirdProductCategory.createThirdCategory("기타", secondProductCategories.get(131)),
                ThirdProductCategory.createThirdCategory("유모차", secondProductCategories.get(132)),
                ThirdProductCategory.createThirdCategory("아기띠", secondProductCategories.get(132)),
                ThirdProductCategory.createThirdCategory("카시트", secondProductCategories.get(132)),
                ThirdProductCategory.createThirdCategory("보행기/쏘서", secondProductCategories.get(132)),
                ThirdProductCategory.createThirdCategory("가구/침대/매트", secondProductCategories.get(132)),
                ThirdProductCategory.createThirdCategory("목욕/구강용품", secondProductCategories.get(132)),
                ThirdProductCategory.createThirdCategory("기저귀", secondProductCategories.get(132)),
                ThirdProductCategory.createThirdCategory("스킨케어", secondProductCategories.get(132)),
                ThirdProductCategory.createThirdCategory("세탁/위생용품", secondProductCategories.get(132)),
                ThirdProductCategory.createThirdCategory("물티슈", secondProductCategories.get(132)),
                ThirdProductCategory.createThirdCategory("기타(유아동용품)", secondProductCategories.get(132)),
                ThirdProductCategory.createThirdCategory("임부의류/속옷", secondProductCategories.get(133)),
                ThirdProductCategory.createThirdCategory("이불/침구", secondProductCategories.get(133)),
                ThirdProductCategory.createThirdCategory("겉싸개/속싸개", secondProductCategories.get(133)),
                ThirdProductCategory.createThirdCategory("손발싸개", secondProductCategories.get(133)),
                ThirdProductCategory.createThirdCategory("배냇저고리", secondProductCategories.get(133)),
                ThirdProductCategory.createThirdCategory("딸랑이/모빌", secondProductCategories.get(133)),
                ThirdProductCategory.createThirdCategory("임부스킨케어", secondProductCategories.get(133)),
                ThirdProductCategory.createThirdCategory("기타(출산/임부용품)", secondProductCategories.get(133)),
                ThirdProductCategory.createThirdCategory("분유수유용품", secondProductCategories.get(134)),
                ThirdProductCategory.createThirdCategory("모유수유용품", secondProductCategories.get(134)),
                ThirdProductCategory.createThirdCategory("젖병세정용품", secondProductCategories.get(134)),
                ThirdProductCategory.createThirdCategory("이유식용품", secondProductCategories.get(134)),
                ThirdProductCategory.createThirdCategory("기타", secondProductCategories.get(134))
        ));

    }
}
