POST http://localhost:8080/product
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVyaXNlZ2VhQG5hdmVyLmNvbSIsImlhdCI6MTY0NzA5NTQzMCwiZXhwIjoxNjQ3MDk3MjMwfQ.LZpdVjKuhViOYTYT2ory5k4l4ClP43ihhP3TxIzQQ4c

#res
#{
#  "statusCode": "OK",
#  "message": null,
#  "result": null
#}
#Response code: 200; Time: 139ms; Content length: 48 bytes


{
  "storeNum": 1,
  "productPhotos": null,
  "productName": "productTempName",
  "firstCategoryNum": 1,
  "secondCategoryNum": 1,
  "thirdCategoryNum": 1,
  "exchangeLocation": "exchangeLocation",
  "productQualityState": "SOLD_ING",
  "productState": "NEW_PRODUCT",
  "exchangeState": "POSSIBILITY",
  "productPrice": 100009,
  "deliveryChargeInPrice": "INCLUDED",
  "productExplanation": "상품설명필드 입니다.",
  "tags": [
    "tag1",
    "tag2"
  ],
  "productAmount": 2
}