PUT http://localhost:8080/product/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVyaXNlZ2VhQG5hdmVyLmNvbSIsImlhdCI6MTY0NzA5NTQzMCwiZXhwIjoxNjQ3MDk3MjMwfQ.LZpdVjKuhViOYTYT2ory5k4l4ClP43ihhP3TxIzQQ4c

#res
#{
#  "statusCode": "OK",
#  "message": null,
#  "result": null
#}
#Response code: 200; Time: 137ms; Content length: 48 bytes

#req
{
  "storeNum": 1,
  "productPhotos": null,
  "productName": "updatedProductTempName",
  "firstCategoryNum": 1,
  "secondCategoryNum": 1,
  "thirdCategoryNum": 1,
  "exchangeLocation": "updatedExchangeLocation",
  "productTradeState": "SOLD_ING",
  "productQualityState": "NEW_PRODUCT",
  "exchangeState": "POSSIBILITY",
  "productPrice": 897762,
  "deliveryChargeInPrice": "INCLUDED",
  "productExplanation": "업데이트 된 상품설명필드 입니다.",
  "tags": [
    "tag3",
    "tag4"
  ],
  "productAmount": 1
}