POST http://localhost:8080/store
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVyaXNlZ2VhQG5hdmVyLmNvbSIsImlhdCI6MTY0NjQ2MTA5NCwiZXhwIjoxNjQ2NDYyODk0fQ.5M0a46KKfNyNvZui5TywQEMEiRPUw2adz-5PAvA8MZk


#res
#{
#  "statusCode": "OK",
#  "message": null,
#  "result": {
#    "storeId": 1,
#    "storeName": "uriStore",
#    "introduceContent": "생성 테스트용 상점"
#  }
#}

# 방식이 id를 입력받는게 아닌 시큐리티 컨택스트에서 가져온 사용자 정보를 토대로 구현하는 것이 맞는것 같다.

#req
{
  "memberId":  4,
  "storeName":  "uriStore",
  "introduceContent":  "생성 테스트용 상점"
}
