PATCH http://localhost:8080/store/introduce
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVyaXNlZ2VhQG5hdmVyLmNvbSIsImlhdCI6MTY1MzYzNjM2MywiZXhwIjoxNjUzNjM4MTYzfQ.n5BSCD-twl0cich-RYXlYNhu1ViJXO21CoLzb1d8zfc

#res
#{
#  "statusCode": "OK",
#  "message": null,
#  "result": null
#}
#Response code: 200; Time: 99ms; Content length: 48 bytes

#req
{
  "updateIntroduceContent":  "생성 테스트용 상점 소개글 수정!!"
}