POST http://localhost:8080/store-visitor
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVyaXNlZ2VhQG5hdmVyLmNvbSIsImlhdCI6MTY0NjU0MDAxOSwiZXhwIjoxNjQ2NTQxODE5fQ.Sku5dpLWpEZTyNhHvoXfEKQuK7qFvWp0OwCKfT9bFxg

#res
#{
#  "statusCode": "OK",
#  "message": null,
#  "result": null
#}

#req
{
  "ownerNum":  1
}
