POST http://localhost:8080/store-inquire
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVyaXNlZ2VhQG5hdmVyLmNvbSIsImlhdCI6MTY1MzYzODU1NCwiZXhwIjoxNjUzNjQwMzU0fQ.Arxdb-8xiJB3zQDVbM02bvxnnH_M63VKLhGf1Iss-jA

#res
#{
#  "statusCode": "CREATED",
#  "message": null,
#  "result": {
#    "inquireNum": 1,
#    "writerName": "testStore",
#    "inquireContent": "테스트용 상점문의 입니다."
#  }
#}

#req
{
  "ownerNum": 2,
  "writerNum": 1,
  "inquireContent": "테스트용 상점문의2 입니다."
}