POST http://localhost:8080/store-inquire
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVyaXNlZ2VhQG5hdmVyLmNvbSIsImlhdCI6MTY0NjQ2MzA3OCwiZXhwIjoxNjQ2NDY0ODc4fQ.a5Y4e-NmdzQRk5Hc7T-R6eRtY4ghyAcwMGJsNc_R4QA

#res
#{
#  "statusCode": "CREATED",
#  "message": null,
#  "result": {
#    "inquireNum": 1,
#    "writerName": "testStore",
#    "inquireContent": "테스트용 상점문의 입니다."
#  }
#}

#req
{
  "ownerNum": 1,
  "writerNum": 2,
  "inquireContent": "테스트용 상점문의 입니다."
}