#POST http://localhost:8080/hall
#Content-Type: application/json
#Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVyaXNlZ2VhQG5hdmVyLmNvbSIsImlhdCI6MTYzNDcyMjYyMCwiZXhwIjoxNjM0NzI0NDIwfQ.f0EKVq-0TRm--0nqxv87tguarUEFLXdGtS5KLSGx0nk
#
#{
#  "lat": 20.5,
#  "lng": 20.5,
#  "name": "title",
#  "originName": "타이틀",
#  "location": "gangnamgu samsungdong",
#  "originLocation": "강남구 삼성동",
#  "city": "seoul",
#  "originCity": "서울",
#  "country": "South Korea",
#  "utc": "1:00",
#  "tags": [
#    "tag1",
#    "tag2"
#  ]
#}