POST http://localhost:8080/login
Content-Type: application/json
#Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVyaXNlZ2VhQG5hdmVyLmNvbSIsImlhdCI6MTYzNDcyMjYyMCwiZXhwIjoxNjM0NzI0NDIwfQ.f0EKVq-0TRm--0nqxv87tguarUEFLXdGtS5KLSGx0nk

{
  "email": "urisegea@naver.com",
  "password": "password"
}