POST http://localhost:8080/following
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVyaXNlZ2VhQG5hdmVyLmNvbSIsImlhdCI6MTY0NzYxMjg2NSwiZXhwIjoxNjQ3NjE0NjY1fQ.dV1wppvJU91L2JEXeaWQeC8CfDtfVs2ZyA8Zox2MHd8

#res
#{
#  "statusCode": "OK",
#  "message": null,
#  "result": null
#}
#Response code: 200; Time: 196ms; Content length: 48 bytes


#req
{
  "followerStoreNum": 1,
  "followedStoreNum": 2
}