POST http://localhost:8080/store-review
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVyaXNlZ2VhQG5hdmVyLmNvbSIsImlhdCI6MTY1MzY0MDM3NiwiZXhwIjoxNjUzNjQyMTc2fQ.3mgLw2JKlZJ7xQPCMDrSA4AjVCbM3nVxteqrsNa7fJw


#res
#{
#  "statusCode": "OK",
#  "message": null,
#  "result": {
#    "reviewNum": 2,
#    "writerNum": 2,
#    "writerThumbnail": null,
#    "writerName": "testStore",
#    "dealScore": 3.0,
#    "productNum": 2,
#    "productName": "productTempName",
#    "reviewContent": "테스트용 상점후기 입니다.",
#    "postingDate": "2022-03-27"
#  }
#}
## 이렇게 생성 요청의 응답이 이렇게 있는것 보단 단건조회가.... 근데 단건조회는 또 없구나. 음...일단 고민해볼것.

#req
{
  "ownerNum": 2,
  "writerNum": 1,
  "dealScore": 4.0,
  "productNum": 9,
  "reviewContent": "1->2테스트용 상점후기2 입니다."
}