GET http://localhost:8080/store/search?keyword=테스트
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVyaXNlZ2VhQG5hdmVyLmNvbSIsImlhdCI6MTY0ODcwNzM2MywiZXhwIjoxNjQ4NzA5MTYzfQ.y28bsfns5yeamcIK3OUiGwI9lj6D6CDjm7S0UbYfFbg

#res
#{
#  "statusCode": "OK",
#  "message": null,
#  "result": {
#    "storeSimpleResponses": [
#      {
#        "storeNum": 1,
#        "storeName": "생성 테스트용 상점명 변경 테스트",
#        "storeThumbnail": {
#          "fileNum": 29,
#          "fileLocation": "https://mins-bunjang-bucket.s3.ap-northeast-2.amazonaws.com/petit-minou-lighthouse-g7a7213b31_1920.jpg"
#        },
#        "productCount": 7,
#        "followerCount": 0,
#        "storeReviewCount": 2
#      }
#    ]
#  }
#}
#
#Response code: 200; Time: 105ms; Content length: 326 bytes